### ISSUE TITLE
Cannot set Mechanize page via Metadata's page method

### ISSUE THREAD

**Issue by derantell** [felipecsl/wombat#42]
When trying to use a pre-fethed Mechanize page as described in the wiki:

``` ruby
Wombat.crawl do
  m = Mechanize.new 
  mp = m.get 'http://www.google.com'
  page mp
end
```

I get an error with this stack trace:

```
crawler.rb:8:in `block in <main>': wrong number of arguments (1 for 0) (ArgumentError)
    from /Users/derantell/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/wombat-2.3.0/lib/wombat/crawler.rb:22:in `instance_eval'
    from /Users/derantell/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/wombat-2.3.0/lib/wombat/crawler.rb:22:in `crawl'
    from /Users/derantell/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/wombat-2.3.0/lib/wombat.rb:13:in `crawl'
    from crawler.rb:4:in `<main>'
```

Using `@metadata_dup.page mp` or renaming `Metadata::page` to something else works, therefore my guess is that the `attr_accessor :page` which `Crawler` includes from `Parser` is found and `method_missing` is never invoked.

Versions used: `ruby 2.1.2`,  `mechanize 2.7.3` and `wombat 2.3.0`

**Comment by acidghost** [comment]
@felipecsl I'm having the same problem here...

**Comment by shashwatsingh** [comment]
Same issue and gem versions same as derantell listed but on Linux 3.16 x86_64 instead. 

Did anyone else have this issue? I tried following - which works, but if someone has a better way, that would be great:

```ruby
module Wombat
  module DSL
    class Metadata
      alias_method :mech_page_ref, :page
    end
  end
end
```

and then used it as follows:

```ruby
data = Wombat.crawl do
  mech_page_ref mech
end
```

**Comment by cyu** [comment]
I just ran into this issue as well.  The issue is that `Wombat::Processing::Parser` defines a `page` accessor (https://github.com/felipecsl/wombat/blob/master/lib/wombat/processing/parser.rb#L24).  Here's my workaround to the issue:

```ruby
# cannot use Wombat#crawl
class Crawler
  include Wombat::Crawler
  og_image xpath: '//html/head/meta[@property = "og:image"]/@content'
  twitter_image_src xpath: '//html/head/meta[@name = "twitter:image:src"]/@content'
end

crawler = Crawler.new
page = crawler.mechanize.get(uri.to_s)
crawler.metadata[:page] = page
result = crawler.crawl
```

**Comment by smileart** [comment]
Workarounds are great and all that, but is there any chance to get it fixed in the project itself? ☹️
